// Generated by build.py - do not edit by hand.
const GRAPH = {
 "nodes": [
  {
   "id": 0,
   "label": "CLAUDE",
   "group": "root",
   "path": "CLAUDE.md",
   "excerpt": "CLAUDE.md This file provides guidance to Claude Code (claude.ai/code) when working with code in this repository. What this repository is This is an Obsidian vault, not a software codebase — there is no build, test, or package-manager tooling here. (\"Lint\" below means a wiki health-check, not code linting.) It is a personal knowledge base of linked Markdown notes, currently centered on Project Jarvis, a proposed multi-agent AI architecture for Shumaker Roofing Co. (Marketing, Sales & Reporting). Obsidian config lives in and should generally be left alone unless the user asks for a settings change. This vault is built as a self-maintaining wiki (Karpathy's \"LLM Wiki\" pattern — see , the…"
  },
  {
   "id": 1,
   "label": "GOALS",
   "group": "root",
   "path": "GOALS.md",
   "excerpt": "Goals Last updated: 2026-07-01 Who I am Operator of Shumaker Roofing Company. Building out an AI agent system (Project Jarvis/Project Jarvis - Agentic OS|Project Jarvis) to run Marketing, Sales & Reporting, with plans to scale into a broader agent roster across the business. Primary goal — Project Jarvis go-live Target: system live by 2026-07-15 (two weeks from today). Success = the full 2-agent system running in production: - Marketing+Sales combined agent (AccuLynx, Google Ads, GoHighLevel, CallRail) - Isolated Reporting agent (Postgres, read-only) Project Jarvis/Implementation Roadmap|Implementation Roadmap paces this at ~7 weeks (Phase 0 through Phase 2) under its original plan.…"
  },
  {
   "id": 2,
   "label": "README",
   "group": "root",
   "path": "README.md",
   "excerpt": "README"
  },
  {
   "id": 3,
   "label": "SETUP GUIDE",
   "group": "root",
   "path": "SETUP GUIDE.md",
   "excerpt": "Welcome to my AI second brain 2.0 template! Follow along the steps to get all set up. VIDEO GUIDE: https://youtu.be/4l8MXYUqGaA STEP 0: Make sure you have Claude Code installed in your terminal & you're logged in to your acc with pro or higher. Follow steps here: https://code.claude.com/docs/en/quickstart FOR MAC: Open Terminal and paste this OR you can use the Claude desktop app and choose this folder as your project workspace. (Same with any other IDE: Antigravity, VS Code, Warp, Etc) Run claude in your terminal, then tell him 'help me install this repo https://github.com/YishenTu/claudian' Restart Obsidian, change your 'Claudian' plugin settings in the Obsidian settings. STEP 1: You can…"
  },
  {
   "id": 4,
   "label": "A Google Ads targeting tactic that cut invalid clicks by 50%",
   "group": "Clippings",
   "path": "Clippings/A Google Ads targeting tactic that cut invalid clicks by 50%.md",
   "excerpt": "After Google said it had already filtered suspicious activity, this unexpected approach restored campaign profitability. Advertisers are estimated to lose $172 billion a year due to ad fraud by 2028. The problem is especially common in industries with high competition and CPCs. One of our clients operated in just such an industry, where high invalid click activity was tanking campaign performance. By adjusting Google Ads targeting, we reduced invalid-click activity by 50% and restored profitable performance. Case study: How we cut invalid clicks by 50% Our client sold book editing and ghostwriting services. The search terms that triggered our ads were relevant and high intent. Yet the…"
  },
  {
   "id": 5,
   "label": "Google June 2026 Spam Update Is Rolling Out",
   "group": "Clippings",
   "path": "Clippings/Google June 2026 Spam Update Is Rolling Out.md",
   "excerpt": "Google has just announced the release of the June 2026 spam update and said it should only take a few days to roll out. Truth is, we kind of saw this coming, although Google would say no, we did not. Google wrote: Released the June 2026 spam update, which applies globally and to all languages. The rollout may take a few days to complete. Google added on LinkedIn: Today we released the June 2026 spam update to Google Search. This is a normal spam update, and it will roll out for all languages and locations. The rollout may take a few days to complete. More information about spam updates can be found over here. June 2026 Google Spam Update Quick Facts Here are the most important things that…"
  },
  {
   "id": 6,
   "label": "Google May 2026 Core Update Rolling Out",
   "group": "Clippings",
   "path": "Clippings/Google May 2026 Core Update Rolling Out.md",
   "excerpt": "Google officially announced the rollout of the May 2026 core update just now, on Thursday at around 11:43 am ET. This core update is expected to take about 2 weeks to roll out. Google said this \"is a regular update designed to better surface relevant, satisfying content for searchers from all types of sites.\" Google posted on LinkedIn: Today we released the May 2026 core update to Google Search. This is a regular update designed to better surface relevant, satisfying content for searchers from all types of sites. The rollout may take up to 2 weeks to complete. Many of you will say you saw it coming a few days ago, I mean, we did cover intense search ranking volatility the morning of I/O and…"
  },
  {
   "id": 7,
   "label": "Google Search Ranking Volatility This Weekend (July 18th)",
   "group": "Clippings",
   "path": "Clippings/Google Search Ranking Volatility This Weekend (July 18th).md",
   "excerpt": "ogle may have released yet another unconfirmed Google search ranking update this weekend. I am seeing some signs of ranking movement from the third-party Google tracking tools and the SEO chatter spiked a bit this weekend. This includes movement on the 18th and 19th of July. The last time we reported on a Google update was the 7-Eleven Google update, which was also unconfirmed. That update seemed to push out some reversals from the January 2026 unconfirmed update"
  },
  {
   "id": 8,
   "label": "How I Built a Second Brain That Maintains Itself",
   "group": "Clippings",
   "path": "Clippings/How I Built a Second Brain That Maintains Itself.md",
   "excerpt": "Most people use AI the same way every time. Upload a document. Ask a question. Get an answer. Close the tab. Tomorrow, you upload the same document. Ask a slightly different question. The AI starts from scratch. No memory of yesterday. No accumulated understanding. No synthesis across everything you’ve ever asked. This is how NotebookLM works. It’s how ChatGPT file uploads work. It’s how most RAG systems work. And it’s fundamentally broken for anyone trying to build knowledge over time. Andrej Karpathy just proposed a better way. And it might be the most useful AI workflow I’ve seen this year. Apr 3 LLM Knowledge Bases Something I'm finding very useful recently: using LLMs to build personal…"
  },
  {
   "id": 9,
   "label": "How competitors target your branded traffic with Google Ads",
   "group": "Clippings",
   "path": "Clippings/How competitors target your branded traffic with Google Ads.md",
   "excerpt": "Learn how dynamic keyword insertion, comparison pages, and brand modifier keywords influence branded searches, and how to defend against them. Your competitors aren’t only bidding on your brand. They’re positioning themselves against you through coordinated tactics across landing pages, ad copy, and Google’s own automation. Much of it looks completely legitimate. Competitive pressure extends beyond keyword bids. Comparison landing pages that never get flagged, dynamic keyword insertion that pulls brand names into headlines, and policy gaps that let competitors appear alongside your brand can quietly erode performance without violating Google’s rules. By the time you notice, the impact may…"
  },
  {
   "id": 10,
   "label": "How to Actually Prompt Fable 5, Straight From the Team That Built It",
   "group": "Clippings",
   "path": "Clippings/How to Actually Prompt Fable 5, Straight From the Team That Built It.md",
   "excerpt": "Fable 5 is back globally as of today, July 1, 2026. Before you open it and run the same prompts you used on Opus 4.8, read this. Anthropic published an official prompting guide for Fable 5 specifically, and the single most important thing it says is that most teams undersell the model by testing it on the wrong things. Fable 5 is not a smarter version of the same tool you have been using. It is a different category of tool that requires a different category of prompt. The teams seeing the best results are not the ones who write better questions. They are the ones who give it harder problems, structure longer runs differently, and understand which behavioral changes in Fable 5 require prompt…"
  },
  {
   "id": 11,
   "label": "How to build an AI-powered content gap analysis workflow",
   "group": "Clippings",
   "path": "Clippings/How to build an AI-powered content gap analysis workflow.md",
   "excerpt": "See how to combine Semrush, Google Search Console, Google Analytics, and Claude to prioritize the content opportunities that matter most. You can publish consistently, follow SEO best practices, and still watch competitors outrank you. More often than not, the problem isn’t content quality. It’s content coverage. Your competitors are answering questions your audience is asking, and you’re not in the conversation yet. That’s where a content gap analysis comes in. It helps you identify topics your competitors rank for that you don’t, then decide which opportunities are actually worth pursuing. Finding the gaps isn’t the hard part. SEO tools make that easy. The challenge is making sense of…"
  },
  {
   "id": 12,
   "label": "How to evaluate Google Ads creative before testing it",
   "group": "Clippings",
   "path": "Clippings/How to evaluate Google Ads creative before testing it.md",
   "excerpt": "Evaluate Google Ads creative with the MOCA framework before it enters testing, so you're experimenting with stronger ideas from the start. If you manage Google Ads, you’re responsible for creative that runs across surfaces and formats that never used to exist. Not long ago, an ad was a single headline and two short descriptions. Today, a single Google ad can include multiple responsive text assets, videos, and images, generating tens of thousands of permutations. We’re often told that when it comes to ad creative, we should just “let the data decide.” So mediocre assets enter rotation, the platform reports on performance, and nobody can explain why an ad works or doesn’t. Part of your job…"
  },
  {
   "id": 13,
   "label": "How to measure prompt-level visibility in AI search",
   "group": "Clippings",
   "path": "Clippings/How to measure prompt-level visibility in AI search.md",
   "excerpt": "You can't measure every AI recommendation, but you can build a reliable picture of your brand's presence. Here's how. AI search doesn’t work like traditional search. A prospect might ask ChatGPT for the best CRM for manufacturing companies, compare options in Google’s AI Mode, refine their requirements over several follow-up questions, and make a shortlist — all without ever clicking a website. If your company appears in those conversations, you’ve influenced the buying process. The challenge is proving it. Prompt-level visibility measurement has become one of the fastest-growing areas of AI search optimization. It’s also one of the most misunderstood. Many vendors promise complete…"
  },
  {
   "id": 14,
   "label": "Karpathy - LLM Knowledge Bases (X thread)",
   "group": "Clippings",
   "path": "Clippings/Karpathy - LLM Knowledge Bases (X thread).md",
   "excerpt": "Post ConversationAndrej Karpathy@karpathy LLM Knowledge Bases Something I'm finding very useful recently: using LLMs to build personal knowledge bases for various topics of research interest. In this way, a large fraction of my recent token throughput is going less into manipulating code, and more into manipulating knowledge (stored as markdown and images). The latest LLMs are quite good at it. So: Data ingest: I index source documents (articles, papers, repos, datasets, images, etc.) into a raw/ directory, then I use an LLM to incrementally \"compile\" a wiki, which is just a collection of.md files in a directory structure. The wiki includes summaries of all the data in raw/, backlinks, and…"
  },
  {
   "id": 15,
   "label": "Karpathy - LLM Wiki (Gist)",
   "group": "Clippings",
   "path": "Clippings/Karpathy - LLM Wiki (Gist).md",
   "excerpt": "LLM Wiki A pattern for building personal knowledge bases using LLMs. This is an idea file, designed to be copied to your own LLM Agent. Its goal communicates the high-level concept, with your agent building specifics collaboratively with you. The Core Idea Most people's experience with LLMs and documents resembles RAG: upload files, retrieve relevant chunks at query time, generate answers. This works but lacks accumulation—the LLM rediscovers knowledge from scratch each time. The different approach here: instead of just retrieving raw documents, the LLM incrementally builds and maintains a persistent wiki—a structured, interlinked markdown collection between you and raw sources. When adding…"
  },
  {
   "id": 16,
   "label": "Local Services Ads come to Google Ads via Performance Max",
   "group": "Clippings",
   "path": "Clippings/Local Services Ads come to Google Ads via Performance Max.md",
   "excerpt": "ogle is moving Local Services Ads (LSAs) into the Google Ads interface, replacing the standalone LSA dashboard with a new Performance Max for pay-per-lead goals campaign designed specifically for local service businesses. What’s happening. Beginning with a phased rollout in August 2026, eligible advertisers will manage Local Services Ads directly within Google Ads. The new campaign type is built exclusively for Local Services advertisers and retains the core characteristics of LSAs:"
  },
  {
   "id": 17,
   "label": "The new SEO rules for bloggers in 2026 Why clarity matters in AI search",
   "group": "Clippings",
   "path": "Clippings/The new SEO rules for bloggers in 2026 Why clarity matters in AI search.md",
   "excerpt": "hy search changed (and why it matters) For years, most bloggers understood SEO through a pretty simple model. A user searched for something. Google returned a list of blue links. The blogger’s job was to create the best page for that query and earn the click. That model still exists. But it’s no longer the only model that matters."
  },
  {
   "id": 18,
   "label": "Web Push advertising in 2026 Market trends and challenges",
   "group": "Clippings",
   "path": "Clippings/Web Push advertising in 2026 Market trends and challenges.md",
   "excerpt": "A look at how Web Push advertising is adapting in 2026 through better compliance, stronger traffic quality, and more mature market growth. RollerAds 20260716 Feature Predictability is not the exact adjective we can apply to Push notifications. One day, they are at their all-time high; another, Google rolls out an update, and everything goes south very quickly. Changes in platform policies have taken many businesses aback. In this article, we answer one of the most pressing questions: Has Web Push lost its momentum, or is it simply evolving — and if so, into what? Let’s take a closer look at the state of the Web Push advertising market and explore its key challenges, major trends, and the…"
  },
  {
   "id": 19,
   "label": "AI Search Visibility Measurement",
   "group": "Marketing",
   "path": "Marketing/AI Search Visibility Measurement.md",
   "excerpt": "AI Search Visibility Measurement ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS The shift AI search (ChatGPT, Google AI Mode, etc.) doesn't have \"rankings\" — the same prompt can return different results depending on conversation history, location, personalization, follow-ups, model version, and time. Visibility is now probabilistic, not deterministic. The right question isn't \"do we rank?\" but \"how often are we included across the conversations that matter?\" 5-step measurement framework 1. Accept there's no \"position 1\" — stop trying to recreate traditional SEO rank reports inside AI answers. 2. Build a prompt library, not a keyword list —…"
  },
  {
   "id": 20,
   "label": "AI-Powered Content Gap Analysis Workflow",
   "group": "Marketing",
   "path": "Marketing/AI-Powered Content Gap Analysis Workflow.md",
   "excerpt": "AI-Powered Content Gap Analysis Workflow ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS The core idea Finding keyword gaps isn't the hard part — SEO tools surface them easily. The hard part is turning thousands of keywords spread across multiple reports into a prioritized roadmap. This workflow combines three data sources with an AI layer (Claude, optionally via MCP) to do that prioritization: Semrush for competitive gaps, Google Search Console for first-party validation, Google Analytics for business context. Two ways to run it: export reports manually and upload them, or (if the platforms are MCP-connected) let Claude pull the data directly.…"
  },
  {
   "id": 21,
   "label": "CallRail Call Audit (June 2026)",
   "group": "Marketing",
   "path": "Marketing/CallRail Call Audit (June 2026).md",
   "excerpt": "CallRail Call Audit (June 2026) ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS First note in the folder — the start of a second-brain wiki for Shumaker Roofing's marketing operations, separate from the architecture notes. See CallRail v3 for the connector this data came from. Method Pulled all calls for the Shumaker Roofing CallRail account ( ) for 2026-06-01 through 2026-06-30 via in the repo. The script computes aggregate stats only — no raw call records (customer names, phone numbers, recordings, transcripts) are written to disk or to this note. Headline numbers | Metric | Result | |---|---| | Total calls | 370 | | Answered | 326 (88%) | |…"
  },
  {
   "id": 22,
   "label": "Defending Branded Search from Competitor Google Ads Tactics",
   "group": "Marketing",
   "path": "Marketing/Defending Branded Search from Competitor Google Ads Tactics.md",
   "excerpt": "Defending Branded Search from Competitor Google Ads Tactics ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS · See also Marketing/Invalid Click Mitigation - Audience Targeting Tactic|Invalid Click Mitigation · Google Ads API · CallRail v3 Three tactics competitors use, all policy-compliant 1. Dynamic keyword insertion (DKI). A competitor bids on your branded terms with DKI enabled; Google auto-inserts your brand name into their ad headline in real time. The competitor never manually wrote your trademark into the ad, so it doesn't clearly violate policy — but to the searcher, the ad looks like it references your brand. Not detectable inside Google…"
  },
  {
   "id": 23,
   "label": "Google Algorithm Updates Tracker",
   "group": "Marketing",
   "path": "Marketing/Google Algorithm Updates Tracker.md",
   "excerpt": "Google Algorithm Updates Tracker ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS Running log of Google Search algorithm updates worth being aware of for Shumaker Roofing's organic visibility. Not every update gets a dedicated note — this is a single append-only tracker, consistent with this vault's log-style pages (e.g. Ingestion Log). Add a new row per update as sources get ingested; don't create a separate page per update unless one has a specific, actionable finding for Shumaker. Log | Date announced | Update | Type | Rollout | Notes | |---|---|---|---|---| | 2026-05-21 | May 2026 Broad Core Update | Core | ~2 weeks | Regular core update…"
  },
  {
   "id": 24,
   "label": "Invalid Click Mitigation - Audience Targeting Tactic",
   "group": "Marketing",
   "path": "Marketing/Invalid Click Mitigation - Audience Targeting Tactic.md",
   "excerpt": "Invalid Click Mitigation - Audience Targeting Tactic ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS · See also Marketing/CallRail Call Audit (June 2026)|CallRail Call Audit (June 2026) · Google Ads API The tactic Add most/all of Google's predefined audiences to a Search campaign, set to \"Targeting\" (not \"Observation\"). Targeting restricts ads to users who both trigger the keyword and fall into a selected audience; Observation only reports on audience behavior without restricting delivery. Why it works: fraudulent/bot traffic cycling through IPs and VPNs typically doesn't build the kind of normal browsing history that lands a user in Google's…"
  },
  {
   "id": 25,
   "label": "MOCA Ad Creative Evaluation Framework",
   "group": "Marketing",
   "path": "Marketing/MOCA Ad Creative Evaluation Framework.md",
   "excerpt": "MOCA Ad Creative Evaluation Framework ⬅ Back to Marketing/Marketing - Overview|Marketing — Overview · Project Jarvis - Agentic OS The core idea \"Let the data decide\" lets mediocre ad creative into testing by default, and nobody can explain afterward why an ad won or lost. MOCA is a pre-test quality filter — a way to apply and defend creative judgment before an ad enters a Google Ads test, not a replacement for testing itself. A high MOCA score doesn't guarantee a winning ad; it means the ad is worth testing. The four pillars 1. Magnetic — does the ad qualify the click before the visit happens? Good ads are selectively attractive: they attract the right buyer and actively repel the wrong one…"
  },
  {
   "id": 26,
   "label": "Marketing - Overview",
   "group": "Marketing",
   "path": "Marketing/Marketing - Overview.md",
   "excerpt": "Marketing — Overview ⬅ Back to Project Jarvis - Agentic OS Central index for Shumaker Roofing Co.'s marketing knowledge base — live channel audits, competitive/tactical playbooks, and anything else marketing-operational rather than architecture-planning. Every note below links back here. This folder is a second-brain wiki in its own right (see Clippings/How I Built a Second Brain That Maintains Itself), distinct from , which covers the agent architecture that will eventually consume this data. Channel audits - Marketing/CallRail Call Audit (June 2026)|CallRail Call Audit (June 2026) — 370 calls audited; found and are 0% populated live, despite being CallRail v3's documented primary…"
  },
  {
   "id": 27,
   "label": "Accelerated Launch Plan (2-Week Sprint)",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Accelerated Launch Plan (2-Week Sprint).md",
   "excerpt": "Accelerated Launch Plan (2-Week Sprint) ⬅ Back to Project Jarvis - Agentic OS The original Implementation Roadmap paces Phase 0→2 (full 2-agent system) at ~7 weeks. The operator's target is go-live 2026-07-15 (14 days from plan date 2026-07-01). This note is the compressed, parallelized version of that plan — what ships day 1, what's deliberately cut, and what follows fast after. The one hard external dependency Google Ads developer token was not yet submitted as of 2026-07-01. Google's official review target is ~2 business days but Caveats flags a known early-2026 backlog stretching to weeks — and that's after submission, before any connector work even starts. Action: submit today,…"
  },
  {
   "id": 28,
   "label": "AccuLynx",
   "group": "Project Jarvis",
   "path": "Project Jarvis/AccuLynx.md",
   "excerpt": "AccuLynx — the flagged \"dealbreaker,\" investigated thoroughly ⬅ Back to Layer 4 - Connectors Overview · Project Jarvis - Agentic OS Verdict Not a dealbreaker. AccuLynx has a documented public REST API v2. Base URL / auth , . Keys are generated in the AccuLynx API settings by a company administrator; each company location requires its own key. Read endpoints relevant to the Sales sub-agent (all confirmed in the public OpenAPI/ index) - (filterable by date range, milestone, sort) and - and milestone history - (supports worksheet + amendments) - - - (high-level financial overview) - (the rep on a job) and - (status-filterable list of reps) - active lead sources, trade/work types, custom fields…"
  },
  {
   "id": 29,
   "label": "Action Items",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Action Items.md",
   "excerpt": "Action Items ⬅ Back to Project Jarvis - Agentic OS Concrete, ownable next-actions blocking the 2026-07-15 go-live (GOALS). Each item below has a single next-action, not a phase's worth of work — see Phase 0 Progress Tracker for the full status log and Accelerated Launch Plan (2-Week Sprint) for the plan these blockers sit inside. Check items off here as they close; the Progress Tracker log is still the place to record what happened. Open 1. Get VPS budget approved - Status: Blocked — on hold since 2026-07-07, no owner action taken yet. Deferred by operator instruction (2026-07-22): don't chase or re-flag this — the operator will report back once it's resolved. Lint/status passes should…"
  },
  {
   "id": 30,
   "label": "CallRail v3",
   "group": "Project Jarvis",
   "path": "Project Jarvis/CallRail v3.md",
   "excerpt": "CallRail v3 ⬅ Back to Layer 4 - Connectors Overview · Project Jarvis - Agentic OS Summary Mature, public API. Used by both the Marketing sub-agent (source/medium/GCLID first-touch) and the Sales sub-agent (lead qualification/call handling) — see Layer 3 - Orchestrator Topology. - Auth: - Key read endpoints: with , , , ; Premium Conversation Intelligence (CI) adds , , - Rate limits: 1,000/hr, 10,000/day (general) - Known roadblocks: Paid API usage tiers (see below); transcripts require Premium CI plan; 25-month data retention Lead-qualification specifics (Sales sub-agent) - — values , , , or ; also usable as a filter/sort key. This is the primary lead-qualification signal as documented — but…"
  },
  {
   "id": 31,
   "label": "Caveats",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Caveats.md",
   "excerpt": "Caveats ⬅ Back to Project Jarvis - Agentic OS - Source quality: Google Ads, GHL, AccuLynx, CallRail, Slack, Anthropic, and Replit facts are drawn from official/primary documentation (several confirmed verbatim against vendor docs). Framework-comparison and hosting claims (e.g., LangGraph \"100M+ runs/month,\" Mac-vs-VPS break-even ranges, Vapi per-minute pricing) come from vendor blogs and should be treated as directional, not audited. - Pricing and rate limits drift. All dollar figures and limits (CallRail tiers, GHL 100/10s, AccuLynx 10/s) were current as of mid-2026; re-verify against live docs before committing budget. - AccuLynx field-level depth is unverified for Shumaker's specific…"
  },
  {
   "id": 32,
   "label": "Fable 5 Prompting Patterns",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Fable 5 Prompting Patterns.md",
   "excerpt": "Fable 5 Prompting Patterns ⬅ Back to Project Jarvis - Agentic OS Operational prompting guidance for Fable 5, the current Anthropic model generation (successor to Opus 4.8, back globally as of 2026-07-01). This isn't Shumaker-specific — it's engineering guidance for how to prompt the model underneath the Layer 2 - Agentic Harness|Claude Agent SDK harness that Project Jarvis is being built on, so it's filed as its own note rather than folded into Layer 2's framework-comparison content. What Fable 5 is actually for Not a faster version of prior models — a different category, suited to sustained, autonomous, multi-stage work that previously fragmented or hallucinated partway through.…"
  },
  {
   "id": 33,
   "label": "GoHighLevel v2",
   "group": "Project Jarvis",
   "path": "Project Jarvis/GoHighLevel v2.md",
   "excerpt": "GoHighLevel (GHL) v2 ⬅ Back to Layer 4 - Connectors Overview · Project Jarvis - Agentic OS Summary Mature, public API. Used by the Marketing sub-agent for funnel stages and lead attribution — see Layer 3 - Orchestrator Topology. - Auth: OAuth2 (Authorization Code) or Private Integration Token; access token expires ~24h, refresh token ~1yr - Key read endpoints: Opportunities/pipelines (funnel stages), Contacts (lead attribution), Conversations - Rate limits: 100 req/10s burst; 200,000/day per app per location - Known roadblocks: - V1 end-of-support 31-Dec-2025 — must use v2 - OAuth advanced features are gated to the Agency Pro plan - scope is available — use it to enforce read-only at the…"
  },
  {
   "id": 34,
   "label": "Google Ads API",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Google Ads API.md",
   "excerpt": "Google Ads API ⬅ Back to Layer 4 - Connectors Overview · Project Jarvis - Agentic OS Summary Mature, fully public API (v24+). Used by the Marketing sub-agent — see Layer 3 - Orchestrator Topology. - Auth: OAuth2 (3-legged or service account) + developer token - Key read endpoints: with GAQL: , , (ROAS), PMax via - Rate limits: 10k ops/batch; access-level quotas (Basic = 15,000 ops/day) - Known roadblock (still open as of 2026-07-24): Developer token requires Google approval (Basic→Standard) before it can hit production accounts at production quota. Token is currently at Explorer Access (confirmed via API Center screenshot, see below) — this tier does not clear the roadblock. Cost is still…"
  },
  {
   "id": 35,
   "label": "Implementation Roadmap",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Implementation Roadmap.md",
   "excerpt": "Step-by-Step Implementation Roadmap ⬅ Back to Project Jarvis - Agentic OS Phase 0 — Foundations (week 1) Provision the VPS; harden (non-root user, firewall, Tailscale, disk encryption); install the Claude Agent SDK runtime; stand up a private git repo for Skills/knowledge files; create a secrets vault (env vars or a managed secrets store — never hardcode). Submit the Google Ads developer-token application on day one (longest external dependency). See Layer 1 - Host Infrastructure, Google Ads API. Phase 1 — Read-only Reporting MVP (weeks 2–3) Build the PostgreSQL Reporting|Postgres MCP server with one read-only query tool against a -only role on a read replica. Wire Slack Bolt in Socket…"
  },
  {
   "id": 36,
   "label": "Ingestion Log",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Ingestion Log.md",
   "excerpt": "Ingestion Log ⬅ Back to Project Jarvis - Agentic OS Tracks every time a raw source in gets read and cross-checked against the wiki, plus any other new-information event (e.g. a live tool/data connection) that changes what a wiki page should say. Raw sources are immutable — the AI reads them but never edits them; this log is where the AI's work on them gets recorded. Log | Date | Source | Action | Result | |---|---|---|---| | 2026-07-03 | | Read in full (surfaced via editor selection). Explains Karpathy's \"LLM Wiki\" pattern: raw sources → AI-maintained wiki → schema, as an alternative to RAG. | Reframed an earlier misread of \"apply Karpathy's approach\" (had been read as \"train an LLM from…"
  },
  {
   "id": 37,
   "label": "Layer 1 - Host Infrastructure",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Layer 1 - Host Infrastructure.md",
   "excerpt": "Layer 1 — Host Infrastructure ⬅ Back to Project Jarvis - Agentic OS Options | Option | Strengths | Weaknesses | Verdict | | ------------------------------------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |…"
  },
  {
   "id": 38,
   "label": "Layer 2 - Agentic Harness",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Layer 2 - Agentic Harness.md",
   "excerpt": "Layer 2 — Agentic Harness & Core Framework ⬅ Back to Project Jarvis - Agentic OS Framework Comparison | Framework | Persistent memory | Vector/knowledge injection | Inter-agent loops | Fit for Jarvis | |---|---|---|---|---| | Claude Agent SDK (Claude Code SDK mode) + MCP | Session persistence + resume/forkSession; CLAUDE.md project memory; automatic context compaction | Skills (progressive disclosure) + MCP-exposed vector stores | First-class subagents with isolated context, per-agent tools/permissions, Task tool delegation | Top pick — native hub-and-spoke, native MCP, least glue code | | LangGraph | Best-in-class durable checkpointing; resumable graphs; survives process crashes | BYO…"
  },
  {
   "id": 39,
   "label": "Layer 3 - Orchestrator Topology",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Layer 3 - Orchestrator Topology.md",
   "excerpt": "Layer 3 — Orchestrator & Sub-Agent Topography ⬅ Back to Project Jarvis - Agentic OS Topology: Hub-and-spoke Jarvis (orchestrator) owns query parsing, routing, and synthesis; sub-agents own a single domain and a single credential set. - Orchestrator (Jarvis) — parses the natural-language query, decomposes it into per-domain sub-questions, dispatches to sub-agents in parallel ( tool), then synthesizes a single answer. Holds no platform credentials itself. - Sub-Agent A — Marketing: Google Ads API (campaign/PMax performance, ROAS), GoHighLevel v2 (funnel stages, lead attribution), CallRail v3 (source/medium/GCLID first-touch). Tools: , , (read-scoped). - Sub-Agent B — Sales: AccuLynx (pipeline…"
  },
  {
   "id": 40,
   "label": "Layer 4 - Connectors Overview",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Layer 4 - Connectors Overview.md",
   "excerpt": "Layer 4 — Connectors & API Feasibility (CRITICAL) ⬅ Back to Project Jarvis - Agentic OS Feasibility Matrix | Platform | API openness | Auth | Key read endpoints | Rate limits | Known roadblocks | |---|---|---|---|---|---| | Google Ads API | Mature, fully public (v24+) | OAuth2 (3-legged or service account) + developer token | w/ GAQL: , , (ROAS), PMax via | 10k ops/batch; access-level quotas (Basic = 15,000 ops/day) | Developer token requires Google approval (Basic→Standard); token cannot hit production accounts until approved; cost in micros (÷1e6) | | GoHighLevel v2 | Mature, public | OAuth2 (Authorization Code) or Private Integration Token; access token expires ~24h, refresh token ~1yr |…"
  },
  {
   "id": 41,
   "label": "Layer 5 - Communication Channels",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Layer 5 - Communication Channels.md",
   "excerpt": "Layer 5 — Communication Channels ⬅ Back to Project Jarvis - Agentic OS Slack (primary) Use Bolt (official SDK; JS/Python/Java). Run in Socket Mode so the agent needs no public inbound URL (ideal on a hardened VPS — see Layer 1 - Host Infrastructure) — requires an app-level token ( ) with plus the bot token ( ). Verify the Slack signing secret on every request. Apply least-privilege scopes. iMessage (secondary, optional) Requires macOS. The robust path is BlueBubbles Server (runs on the Mac, exposes a REST API with reactions/edits/media; needs Full Disk Access + a Firebase project for push). This is the single strongest reason to introduce a Mac Mini — see Layer 1 - Host Infrastructure. Note…"
  },
  {
   "id": 42,
   "label": "Layer 6 - Skills and Knowledge Injection",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Layer 6 - Skills and Knowledge Injection.md",
   "excerpt": "Layer 6 — Skills, Vector Stores & Knowledge Injection ⬅ Back to Project Jarvis - Agentic OS Goal Sub-agents must never hallucinate business logic (pricing, the definition of a \"qualified lead,\" company terminology). Approach Author business logic as Markdown \"Skills\" / knowledge files, version-controlled in git. One file per concept: - - - - (e.g., exact ROAS/CAC formulas) - (mapping AccuLynx milestones → revenue stages) Two-tier retrieval (mirrors how Hermes and Claude Skills work — see Layer 2 - Agentic Harness) 1. Always-on core memory — small, authoritative definitions (what counts as a qualified lead; the canonical KPI formulas) injected into the system prompt at session start so there…"
  },
  {
   "id": 43,
   "label": "Phase 0 Progress Tracker",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Phase 0 Progress Tracker.md",
   "excerpt": "Phase 0 Progress Tracker ⬅ Back to Project Jarvis - Agentic OS Tracks real-world execution status against the infra items in Implementation Roadmap Phase 0, now running on the compressed timeline in Accelerated Launch Plan (2-Week Sprint) (go-live target 2026-07-15). Update the checkboxes and dates as items move — this note is the \"reality\" layer on top of the plan. For the two current blockers as single ownable next-actions, see Action Items. Checklist - [ ] Submit Google Ads developer-token application — longest external dependency on the critical path. Google Ads API / Recommendations #3 flagged applying \"week 1\"; Caveats notes an early-2026 review backlog. Status as of 2026-07-01:…"
  },
  {
   "id": 44,
   "label": "PostgreSQL Reporting",
   "group": "Project Jarvis",
   "path": "Project Jarvis/PostgreSQL Reporting.md",
   "excerpt": "PostgreSQL — secure read-only text-to-SQL ⬅ Back to Layer 4 - Connectors Overview · Project Jarvis - Agentic OS Summary Backs the Reporting sub-agent — see Layer 3 - Orchestrator Topology. This connector carries the highest blast radius of the five (raw DB access), so it is isolated from day one and shipped first as the MVP (Implementation Roadmap Phase 1). - Auth: DB role credentials - Key read endpoints: Read-only on ROI dashboard - Rate limits: DB-configured - Known roadblock: Text-to-SQL injection/write risk Implementation Map the ROI dashboard DB into the Reporting agent through a Postgres MCP server that exposes a single read-only tool, backed by a database role created with only (no…"
  },
  {
   "id": 45,
   "label": "Project Jarvis - Agentic OS",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Project Jarvis - Agentic OS.md",
   "excerpt": "Project Jarvis — Agentic OS Central index for the multi-agent AI architecture proposed for Shumaker Roofing Co. (Marketing, Sales & Reporting). Every note below links back here. Click through for full detail + sources. TL;DR Build it as Layer 2 - Agentic Harness|Claude Agent SDK (orchestrator + subagents) running on a Layer 1 - Host Infrastructure|cloud VPS (Hetzner/DigitalOcean), connecting to every platform through read-scoped MCP servers. The AccuLynx \"dealbreaker\" is false — see AccuLynx. Start with a 2-agent split (Layer 3 - Orchestrator Topology|Marketing+Sales combined + isolated Reporting agent). → Full breakdown: TLDR and Key Findings --- The Six Layers | Layer | Note | One-line…"
  },
  {
   "id": 46,
   "label": "Recommendations",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Recommendations.md",
   "excerpt": "Recommendations ⬅ Back to Project Jarvis - Agentic OS 1. Adopt Claude Agent SDK on a Hetzner/DigitalOcean VPS now; defer the Mac Mini unless iMessage delivery is a hard requirement from the principals. See Layer 1 - Host Infrastructure, Layer 2 - Agentic Harness. 2. Kill the \"AccuLynx is impossible\" assumption — it has a documented read API. Apply for an AccuLynx Partner Program slot early to raise rate limits and get a (limited) support channel. See AccuLynx. 3. Apply for the Google Ads developer token in week 1 — Google's official review target is ~2 business days, but an acknowledged early-2026 backlog can stretch it to weeks; this is the longest external dependency on the critical path.…"
  },
  {
   "id": 47,
   "label": "Routing Example",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Routing Example.md",
   "excerpt": "Multi-Agent Routing Strategy (worked example) ⬅ Back to Project Jarvis - Agentic OS Query: \"How is Victor's pipeline looking compared to our Google Ads spend this week?\" 1. Channel → Orchestrator. Slack Bolt (Socket Mode) receives the message, verifies the signing secret, strips/escapes the raw text, and hands a structured request to Jarvis. See Layer 5 - Communication Channels. 2. Query parsing & decomposition. Jarvis identifies two domains (Sales: \"Victor's pipeline\"; Marketing: \"Google Ads spend\") and one time window (\"this week\" → resolves to an explicit ISO date range). It resolves \"Victor\" against the AccuLynx list to a user GUID (and confirms one match to avoid ambiguity). 3.…"
  },
  {
   "id": 48,
   "label": "Security and Guardrails",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Security and Guardrails.md",
   "excerpt": "Security & Guardrail Protocol ⬅ Back to Project Jarvis - Agentic OS Enforcing read-only (defense in depth — never rely on the prompt alone) 1. Database layer: dedicated Postgres role with only ; no / / / ; point at a read replica; set and a row-limit; consider query rewriting to restrict accessible tables/columns. See PostgreSQL Reporting. 2. Tool layer: MCP servers for AccuLynx/GHL/Google Ads/CallRail implement only GET/read tools — write endpoints are simply never coded, so the model cannot call them regardless of what it \"decides.\" Use the SDK allowlist (e.g., ) rather than broad permissions; prefer explicit allowlists over . 3. Prompt layer: system-prompt instruction that the agent is…"
  },
  {
   "id": 49,
   "label": "TLDR and Key Findings",
   "group": "Project Jarvis",
   "path": "Project Jarvis/TLDR and Key Findings.md",
   "excerpt": "TL;DR and Key Findings ⬅ Back to Project Jarvis - Agentic OS TL;DR Build it as Claude Agent SDK (orchestrator + subagents) running on a cloud VPS (Hetzner/DigitalOcean), connecting to every platform through read-scoped MCP servers. This gives the lowest-friction path to a 24/7, auditable, hub-and-spoke system. The Mac Mini is only justified if iMessage delivery or local browser/screen automation is a hard requirement. The AccuLynx \"dealbreaker\" is FALSE. AccuLynx publishes a documented public REST API v2 ( , Bearer API-key auth) with read endpoints for Jobs, Milestones, Financials, Invoices, Payments, Sales Owner, and Users — everything the Sales sub-agent needs. The real constraints are…"
  },
  {
   "id": 50,
   "label": "Voice App (Local Prototype)",
   "group": "Project Jarvis",
   "path": "Project Jarvis/Voice App (Local Prototype).md",
   "excerpt": "Voice App (Local Prototype) ⬅ Back to Project Jarvis - Agentic OS What it is (vault root, sibling to ) is a local Electron desktop app for talking to a scoped slice of Jarvis by chat or voice, built to test the experience on this machine before the VPS exists. It embeds the Layer 2 - Agentic Harness|Claude Agent SDK directly rather than going through Claude Code, with a chat log, text input, and a mic button (Web Speech API for STT, for TTS) — no external voice vendor needed for this local pass. Scope: Marketing, Strategy, and Info only Only two MCP servers are ever registered with the Agent SDK session: GoHighLevel v2|ghl-mcp-server and CallRail v3|callrail-mcp-server. AccuLynx (sales…"
  },
  {
   "id": 51,
   "label": "README",
   "group": "jarvis-dashboard",
   "path": "jarvis-dashboard/README.md",
   "excerpt": "jarvis-dashboard Browser-based local dashboard for Project Jarvis — Step 1 of the rebuild that replaces the Electron prototype (see ). Same reasoning core (Claude Agent SDK) and same restricted MCP tool set, now served as a web page instead of a desktop window, over WebSocket so future phases (live knowledge graph, tool-call events, scheduled brief cards) have a channel to push updates on. Scope: Marketing, Strategy, and Info only Same as : only and are ever registered with the Agent SDK session. AccuLynx and any Postgres/reporting/infra tool are not wired in. Step 2 (done): now sets an explicit allow-list on the Agent SDK's built-in toolset — only and are available (for live…"
  },
  {
   "id": 52,
   "label": "system-prompt",
   "group": "jarvis-dashboard",
   "path": "jarvis-dashboard/system-prompt.md",
   "excerpt": "You are Jarvis, a local assistant for Shumaker Roofing Co., scoped strictly to Marketing, Strategy, and Info. This is the browser-based dashboard rebuild of the earlier prototype — same persona and scope rules apply. In scope - Marketing performance: GoHighLevel funnel/lead/opportunity data, CallRail call/lead-source data, SEO and competitive research via Semrush, ad and traffic reporting via Supermetrics (both only available once their own API keys are configured — say plainly if a tool call for either fails because a key is missing, don't guess at numbers instead). - Live web search/fetch for marketing trends, industry news, and general research — you have real web access, use it rather…"
  },
  {
   "id": 53,
   "label": "README",
   "group": "mcp-servers",
   "path": "mcp-servers/acculynx-mcp-server/README.md",
   "excerpt": "acculynx-mcp-server Local stdio MCP server exposing read-only AccuLynx v2 tools for Project Jarvis's Sales sub-agent — see for the connector's role, auth, rate-limit, and blocker notes. Tools | Tool | Wraps | |---|---| | | | | | | | | | | | | | | | | | | | | | | | | | | | | | | All read-only ( ). No write/mutation tools are exposed — this is a hard requirement, not a style choice: AccuLynx API keys are write-capable with no read-only scope (AccuLynx's own words: \"Your API Key can be used by anyone to expose or manipulate your company data\"), so read-only must be enforced entirely at this tool layer. See . Lead sources, trade/work types, and custom fields are documented as available in…"
  },
  {
   "id": 54,
   "label": "README",
   "group": "mcp-servers",
   "path": "mcp-servers/callrail-mcp-server/README.md",
   "excerpt": "callrail-mcp-server Local stdio MCP server exposing read-only CallRail v3 tools for Project Jarvis's Marketing and Sales sub-agents — see Project Jarvis/CallRail v3.md for the connector's role, auth, rate-limit, and pricing-tier notes. Tools | Tool | Wraps | |---|---| | | | | | | | | | | | | | | | | | | All read-only ( ). No write/mutation tools are exposed. and are confirmed working against the live Shumaker Roofing account (see \"Live account\"/\"Live audit\" sections and ). The other four tools wrap endpoints from CallRail's public v3 API reference that aren't yet live-tested from this codebase — treat their exact response shape as unconfirmed until exercised once via . Important caveat…"
  },
  {
   "id": 55,
   "label": "README",
   "group": "mcp-servers",
   "path": "mcp-servers/ghl-mcp-server/README.md",
   "excerpt": "ghl-mcp-server Local stdio MCP server exposing read-only GoHighLevel v2 tools for Project Jarvis's Marketing sub-agent — see for the connector's role, auth, and rate-limit notes. Tools | Tool | Wraps | |---|---| | | | | | | | | | | | | | | | | | | All read-only ( ). No write/mutation tools are exposed. Setup 1. In GHL: Settings → Private Integrations → create a token scoped to , , . 2. and fill in and . 3. 4. Run standalone (smoke test) Opens the MCP Inspector UI so you can call tools by hand before wiring it into Claude Code. Connect to Claude Code Claude Code launches it as a subprocess and passes your current shell env — make sure / are exported in the shell you run from, or set them in…"
  },
  {
   "id": 56,
   "label": "README",
   "group": "mcp-servers",
   "path": "mcp-servers/semrush-mcp-server/README.md",
   "excerpt": "semrush-mcp-server Local stdio MCP server exposing read-only Semrush Analytics API tools for Project Jarvis's Marketing sub-agent — SEO/competitive research (domain overview, organic & paid keyword data). Tools | Tool | Wraps | Confidence | |---|---|---| | | | Confirmed shape (verified against Semrush's documented example) | | | (generic) | Passthrough — caller supplies ; not independently verified per report type | Both read-only ( ). No write/mutation tools are exposed — Semrush's classic API is read-only by nature (it serves reports, it doesn't accept writes). Important caveat: only has a request/response shape confirmed against Semrush's own documentation as of this server's build. is a…"
  },
  {
   "id": 57,
   "label": "README",
   "group": "mcp-servers",
   "path": "mcp-servers/supermetrics-mcp-server/README.md",
   "excerpt": "supermetrics-mcp-server Local stdio MCP server exposing a read-only Supermetrics API v2 query tool for Project Jarvis's Marketing sub-agent — pulls data from whatever sources (Google Ads, etc.) are configured on the connected Supermetrics account. Tools | Tool | Wraps | Confidence | |---|---|---| | | | Base URL, auth, and core params ( , , , , , , , ) confirmed against Supermetrics' docs. Not yet live-tested from this codebase. | Read-only ( ). No write/mutation tools are exposed. Important gap vs. the claude.ai Supermetrics connector: that connector exposes , , and tools so an agent can find valid / /field names on the fly. This server does not implement equivalents (their exact REST shape…"
  },
  {
   "id": 58,
   "label": "README",
   "group": "voice-app",
   "path": "voice-app/README.md",
   "excerpt": "voice-app — Jarvis Lite (local prototype) A local Electron desktop app for talking to a scoped slice of Project Jarvis by chat or voice — Marketing, Strategy, and Info only. No sales pipeline (AccuLynx), reporting (Postgres), or infra tools are wired in. This is the local rehearsal for Layer 5 - Communication Channels's Phase 5 voice bolt-on, run against this machine instead of the VPS (which is still on hold pending budget approval — see ). Once that unblocks, the same pattern (Agent SDK core + restricted MCP tool set + scoped system prompt) promotes to the real Marketing+Sales agent with Vapi/ElevenLabs at the transport edge. What's wired in - (GoHighLevel — contacts, opportunities,…"
  },
  {
   "id": 59,
   "label": "system-prompt",
   "group": "voice-app",
   "path": "voice-app/system-prompt.md",
   "excerpt": "You are Jarvis Lite, a local prototype voice+chat assistant for Shumaker Roofing Co., scoped strictly to Marketing, Strategy, and Info. In scope - Marketing performance: GoHighLevel funnel/lead/opportunity data, CallRail call/lead-source data, SEO and competitive research via Semrush, ad and traffic reporting via Supermetrics. - Marketing strategy discussion: campaign ideas, positioning, content direction, general \"what should we do about X\" marketing questions. - General info lookups and explanations that support the above. Out of scope — decline and redirect You do not have tools for, and must not attempt to answer with fabricated numbers on: - Sales pipeline / financials (AccuLynx job…"
  }
 ],
 "links": [
  {
   "source": 0,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 28,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 30,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 31,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 33,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 34,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 35,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 44,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 46,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 47,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 48,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 28,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 35,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 39,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 43,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 45,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 46,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 51,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 54,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 55,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 56,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 57,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 3,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 3,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 8,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 10,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 11,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 11,
   "reason": "mention"
  },
  {
   "source": 11,
   "target": 20,
   "reason": "mention"
  },
  {
   "source": 11,
   "target": 35,
   "reason": "mention"
  },
  {
   "source": 11,
   "target": 46,
   "reason": "mention"
  },
  {
   "source": 13,
   "target": 46,
   "reason": "mention"
  },
  {
   "source": 8,
   "target": 15,
   "reason": "wikilink"
  },
  {
   "source": 14,
   "target": 15,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 15,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 15,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 16,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 18,
   "reason": "mention"
  },
  {
   "source": 19,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 13,
   "target": 19,
   "reason": "mention"
  },
  {
   "source": 19,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 1,
   "target": 20,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 20,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 28,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 42,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 46,
   "reason": "mention"
  },
  {
   "source": 21,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 21,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 21,
   "target": 30,
   "reason": "wikilink"
  },
  {
   "source": 21,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 22,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 22,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 22,
   "target": 30,
   "reason": "wikilink"
  },
  {
   "source": 22,
   "target": 34,
   "reason": "wikilink"
  },
  {
   "source": 9,
   "target": 22,
   "reason": "mention"
  },
  {
   "source": 22,
   "target": 24,
   "reason": "mention"
  },
  {
   "source": 22,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 23,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 23,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 5,
   "target": 23,
   "reason": "mention"
  },
  {
   "source": 6,
   "target": 23,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 23,
   "reason": "mention"
  },
  {
   "source": 23,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 24,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 24,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 24,
   "target": 34,
   "reason": "wikilink"
  },
  {
   "source": 24,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 24,
   "target": 31,
   "reason": "mention"
  },
  {
   "source": 25,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 25,
   "target": 34,
   "reason": "wikilink"
  },
  {
   "source": 12,
   "target": 25,
   "reason": "mention"
  },
  {
   "source": 22,
   "target": 25,
   "reason": "mention"
  },
  {
   "source": 24,
   "target": 25,
   "reason": "mention"
  },
  {
   "source": 25,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 25,
   "target": 46,
   "reason": "mention"
  },
  {
   "source": 26,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 26,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 26,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 26,
   "target": 30,
   "reason": "wikilink"
  },
  {
   "source": 26,
   "target": 34,
   "reason": "wikilink"
  },
  {
   "source": 1,
   "target": 26,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 8,
   "target": 26,
   "reason": "mention"
  },
  {
   "source": 27,
   "target": 41,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 37,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 30,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 31,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 33,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 28,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 35,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 27,
   "reason": "mention"
  },
  {
   "source": 1,
   "target": 27,
   "reason": "mention"
  },
  {
   "source": 27,
   "target": 42,
   "reason": "mention"
  },
  {
   "source": 27,
   "target": 44,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 40,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 31,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 35,
   "reason": "wikilink"
  },
  {
   "source": 29,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 27,
   "target": 29,
   "reason": "wikilink"
  },
  {
   "source": 29,
   "target": 37,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 29,
   "reason": "wikilink"
  },
  {
   "source": 29,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 1,
   "target": 29,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 29,
   "reason": "mention"
  },
  {
   "source": 30,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 40,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 31,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 31,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 31,
   "target": 38,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 38,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 42,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 32,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 32,
   "reason": "mention"
  },
  {
   "source": 10,
   "target": 32,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 32,
   "reason": "mention"
  },
  {
   "source": 33,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 40,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 40,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 34,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 16,
   "target": 34,
   "reason": "mention"
  },
  {
   "source": 35,
   "target": 41,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 44,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 37,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 35,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 35,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 42,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 35,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 40,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 1,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 41,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 36,
   "reason": "wikilink"
  },
  {
   "source": 36,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 2,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 5,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 6,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 8,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 9,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 10,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 11,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 12,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 13,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 16,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 17,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 18,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 19,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 20,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 22,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 24,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 25,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 32,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 35,
   "target": 36,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 38,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 42,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 51,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 52,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 54,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 55,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 56,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 57,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 36,
   "target": 59,
   "reason": "mention"
  },
  {
   "source": 37,
   "target": 41,
   "reason": "wikilink"
  },
  {
   "source": 31,
   "target": 37,
   "reason": "wikilink"
  },
  {
   "source": 37,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 37,
   "target": 38,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 40,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 38,
   "reason": "mention"
  },
  {
   "source": 39,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 39,
   "target": 44,
   "reason": "wikilink"
  },
  {
   "source": 39,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 39,
   "reason": "wikilink"
  },
  {
   "source": 40,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 40,
   "target": 44,
   "reason": "wikilink"
  },
  {
   "source": 40,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 41,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 41,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 41,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 41,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 51,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 52,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 54,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 55,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 56,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 57,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 59,
   "reason": "mention"
  },
  {
   "source": 42,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 42,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 42,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 42,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 42,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 43,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 37,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 31,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 42,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 43,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 43,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 43,
   "reason": "mention"
  },
  {
   "source": 44,
   "target": 45,
   "reason": "wikilink"
  },
  {
   "source": 44,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 45,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 45,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 45,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 45,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 45,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 44,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 37,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 46,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 34,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 46,
   "reason": "wikilink"
  },
  {
   "source": 41,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 42,
   "target": 47,
   "reason": "wikilink"
  },
  {
   "source": 39,
   "target": 48,
   "reason": "wikilink"
  },
  {
   "source": 48,
   "target": 52,
   "reason": "mention"
  },
  {
   "source": 48,
   "target": 59,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 40,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 48,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 39,
   "target": 49,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 49,
   "reason": "mention"
  },
  {
   "source": 30,
   "target": 49,
   "reason": "mention"
  },
  {
   "source": 33,
   "target": 49,
   "reason": "mention"
  },
  {
   "source": 41,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 38,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 30,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 33,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 28,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 43,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 35,
   "target": 50,
   "reason": "wikilink"
  },
  {
   "source": 0,
   "target": 50,
   "reason": "mention"
  },
  {
   "source": 2,
   "target": 50,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 51,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 52,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 54,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 55,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 56,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 57,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 50,
   "target": 59,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 51,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 51,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 52,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 31,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 48,
   "target": 53,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 54,
   "reason": "mention"
  },
  {
   "source": 30,
   "target": 54,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 55,
   "reason": "mention"
  },
  {
   "source": 33,
   "target": 55,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 56,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 57,
   "reason": "mention"
  },
  {
   "source": 34,
   "target": 57,
   "reason": "mention"
  },
  {
   "source": 0,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 43,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 51,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 52,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 53,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 54,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 55,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 56,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 57,
   "target": 58,
   "reason": "mention"
  },
  {
   "source": 58,
   "target": 59,
   "reason": "mention"
  },
  {
   "source": 28,
   "target": 59,
   "reason": "mention"
  },
  {
   "source": 5,
   "target": 6,
   "reason": "shared-link"
  },
  {
   "source": 5,
   "target": 7,
   "reason": "shared-link"
  },
  {
   "source": 6,
   "target": 7,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 20,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 21,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 22,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 23,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 24,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 25,
   "reason": "shared-link"
  },
  {
   "source": 20,
   "target": 21,
   "reason": "shared-link"
  },
  {
   "source": 20,
   "target": 22,
   "reason": "shared-link"
  },
  {
   "source": 20,
   "target": 24,
   "reason": "shared-link"
  },
  {
   "source": 20,
   "target": 25,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 22,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 23,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 24,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 25,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 36,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 23,
   "reason": "shared-link"
  },
  {
   "source": 23,
   "target": 24,
   "reason": "shared-link"
  },
  {
   "source": 23,
   "target": 25,
   "reason": "shared-link"
  },
  {
   "source": 19,
   "target": 30,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 30,
   "reason": "shared-link"
  },
  {
   "source": 20,
   "target": 29,
   "reason": "shared-link"
  },
  {
   "source": 20,
   "target": 43,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 29,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 36,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 27,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 42,
   "reason": "shared-link"
  },
  {
   "source": 21,
   "target": 43,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 36,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 42,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 27,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 29,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 27,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 29,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 27,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 34,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 34,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 34,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 34,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 39,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 22,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 39,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 24,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 25,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 25,
   "target": 39,
   "reason": "shared-link"
  },
  {
   "source": 25,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 25,
   "target": 43,
   "reason": "shared-link"
  },
  {
   "source": 25,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 39,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 26,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 35,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 36,
   "target": 39,
   "reason": "shared-link"
  },
  {
   "source": 36,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 39,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 39,
   "target": 43,
   "reason": "shared-link"
  },
  {
   "source": 39,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 40,
   "target": 43,
   "reason": "shared-link"
  },
  {
   "source": 40,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 40,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 43,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 46,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 23,
   "target": 43,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 58,
   "reason": "shared-link"
  },
  {
   "source": 35,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 35,
   "target": 58,
   "reason": "shared-link"
  },
  {
   "source": 36,
   "target": 37,
   "reason": "shared-link"
  },
  {
   "source": 36,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 37,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 37,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 37,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 37,
   "target": 58,
   "reason": "shared-link"
  },
  {
   "source": 43,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 45,
   "target": 58,
   "reason": "shared-link"
  },
  {
   "source": 47,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 47,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 47,
   "target": 58,
   "reason": "shared-link"
  },
  {
   "source": 49,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 49,
   "target": 58,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 41,
   "reason": "shared-link"
  },
  {
   "source": 29,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 41,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 39,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 38,
   "reason": "shared-link"
  },
  {
   "source": 28,
   "target": 37,
   "reason": "shared-link"
  },
  {
   "source": 28,
   "target": 38,
   "reason": "shared-link"
  },
  {
   "source": 27,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 39,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 40,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 46,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 28,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 39,
   "target": 41,
   "reason": "shared-link"
  },
  {
   "source": 41,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 43,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 44,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 28,
   "target": 30,
   "reason": "shared-link"
  },
  {
   "source": 28,
   "target": 33,
   "reason": "shared-link"
  },
  {
   "source": 28,
   "target": 34,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 33,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 38,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 33,
   "target": 34,
   "reason": "shared-link"
  },
  {
   "source": 33,
   "target": 38,
   "reason": "shared-link"
  },
  {
   "source": 33,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 34,
   "target": 38,
   "reason": "shared-link"
  },
  {
   "source": 34,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 34,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 36,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 38,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 44,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 33,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 34,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 35,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 36,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 33,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 40,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 44,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 46,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 46,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 32,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 30,
   "target": 48,
   "reason": "shared-link"
  },
  {
   "source": 33,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 35,
   "target": 38,
   "reason": "shared-link"
  },
  {
   "source": 38,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 38,
   "target": 48,
   "reason": "shared-link"
  },
  {
   "source": 44,
   "target": 47,
   "reason": "shared-link"
  },
  {
   "source": 47,
   "target": 48,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 42,
   "reason": "shared-link"
  },
  {
   "source": 31,
   "target": 50,
   "reason": "shared-link"
  },
  {
   "source": 32,
   "target": 37,
   "reason": "shared-link"
  },
  {
   "source": 37,
   "target": 42,
   "reason": "shared-link"
  },
  {
   "source": 42,
   "target": 49,
   "reason": "shared-link"
  },
  {
   "source": 42,
   "target": 50,
   "reason": "shared-link"
  }
 ]
};
